### ISSUE TITLE
Release OIS v2.2.0

### ISSUE THREAD

**Issue by dcroote** [api3dao/ois#101]
We will need a release after #100 is closed in order to then import the updated OIS package and its types into Airnode and complete https://github.com/api3dao/airnode/issues/1800

Since #100 is a relaxation of a requirement (i.e. it is not breaking and all prior OIS configurations will still be valid), I think this OIS release can be minor instead of major, hence my suggestion of `2.2.0`.

**Comment by bbenligiray** [comment]
Agreed

**Comment by dcroote** [comment]
Closing and moving to Done as the [GitHub release is live](https://github.com/api3dao/ois/releases/tag/v2.2.0) and the npm package has been successfully used in https://github.com/api3dao/airnode/pull/1888
