### ISSUE TITLE
Invalid zod error path

### ISSUE THREAD

**Issue by Siegrift** [api3dao/ois#105]
https://github.com/api3dao/ois/blob/0f2eb7aa762e7eabb0ffd4248315421753317c3d/src/ois.ts#L346

The above error path should not start with `ois`.

**Comment by dcroote** [comment]
There are 8 more instances where the error `path` starts with `'ois'` which I agree is a bug as illustrated by the duplicate `ois` in the error path when validating a full `config.json` file.

Below is an example where I used [secrets.valid.env](https://github.com/api3dao/airnode/blob/v0.12.0/packages/airnode-validator/test/fixtures/secrets.valid.env) and changed the following in [config.valid.json](https://github.com/api3dao/airnode/blob/v0.12.0/packages/airnode-validator/test/fixtures/config.valid.json):

```diff
<                 "in": "path",
<                 "name": "id"
---
>                 "in": "query",
>                 "name": "localization"
```
and ran:
```
npx @api3/airnode-validator@0.12.0 --config config.valid.json --secrets secrets.valid.env
```
which yielded
```json
  {
    "code": "custom",
    "message": "Parameter \"sparkline\" in \"query\" is used in both \"parameters\" and \"fixedOperationParameters\"",
    "path": [
      "ois",
      0,
      "ois",
      "endpoints",
      0,
      "parameters",
      0
    ]
  },
  {
    "code": "custom",
    "message": "Parameter \"sparkline\" in \"query\" is used in both \"parameters\" and \"fixedOperationParameters\"",
    "path": [
      "ois",
      0,
      "ois",
      "endpoints",
      0,
      "fixedOperationParameters",
      5
    ]
  },
  {
    "code": "custom",
    "message": "Parameter \"id\" not found in \"fixedOperationParameters\" or \"parameters\"",
    "path": [
      "ois",
      0,
      "ois",
      "endpoints",
      0
    ]
  }
```
