### ISSUE TITLE
api call skip not implemented for postProcessing V2

### ISSUE THREAD

**Issue by Ashar2shahid** [api3dao/ois#129]
postprocessingV2 currently cannot skip api call https://github.com/api3dao/ois/blob/9343c95235ae6cb1c335603918dae74871329721/src/ois.ts#L425C18-L425C46

@Siegrift

**Comment by Siegrift** [comment]
Thanks. I opened a PR https://github.com/api3dao/ois/pull/130 for this. As I mention in the PR description, you can use the legacy processing schema in case you want to skip the API call.

What were you trying to achieve when you encountered this error?

**Comment by Ashar2shahid** [comment]
> Thanks. I opened a PR #130 for this. As I mention in the PR description, you can use the legacy processing schema in case you want to skip the API call.
> 
> What were you trying to achieve when you encountered this error?

was working on a special usecase that calls blockchain data which needed to skip API call
