### ISSUE TITLE
Publish OIS package

### ISSUE THREAD

**Issue by Siegrift** [api3dao/ois#2]
Blocked by https://github.com/api3dao/airnode/issues/1209

**Comment by aquarat** [comment]
Just published the npmjs packages. Build the docker images now.

**Comment by amarthadan** [comment]
Can you assign milestone, priority, size, and iteration?

**Comment by Siegrift** [comment]
Yeah, except for milestone because that is purely Airnode repository thing.

**Comment by aquarat** [comment]
I'm just noting here that I've seen this.

**Comment by aquarat** [comment]
This has now been published: 
https://www.npmjs.com/package/@api3/ois
and https://github.com/api3dao/ois/releases/tag/v1.0.0

**Comment by kolenic-martin** [comment]
@Siegrift let me know when this is ready for testing :)

**Comment by Siegrift** [comment]
I think there is not much to test here apart from that it was published right, which I've done as part of the review. I think this can be moved to DONE.

I'll need your help to test https://github.com/api3dao/airnode/issues/1274 though :)

**Comment by Siegrift** [comment]
I've confirmed the package is published correctly and can be used in a test project.

Closing.
