### ISSUE TITLE
Release v1.4.0

### ISSUE THREAD

**Issue by dcroote** [api3dao/ois#57]
Necessary to implement `_minConfirmations` and `_gasPrice` on the Airnode side in https://github.com/api3dao/airnode/issues/1393 and https://github.com/api3dao/airnode/issues/1492, respectively.

**Comment by dcroote** [comment]
@aquarat could I bother you to release v1.4.0? It will contain dependency bumps (an important one of which is [zod](https://github.com/api3dao/ois/pull/54)), and the addition of two new reserved parameters: [_minConfirmations](https://github.com/api3dao/ois/pull/52) and [_gasPrice](https://github.com/api3dao/ois/pull/56). The addition of these two reserved parameters are part of Airnode v0.10.0.

**Comment by aquarat** [comment]
Done :)

**Comment by dcroote** [comment]
> Done :)

Thanks! I can confirm I can use it in Airnode (so via npm), though perhaps we also want a corresponding GitHub release?

**Comment by aquarat** [comment]
Apologies, I just saw this, I've created the release 🙈

**Comment by dcroote** [comment]
Thanks! Moving this to Done as I've test it in Airnode.
